# Generated by Django 4.2.13 on 2024-06-15 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_language_alter_mymodel_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mymodel',
        ),
    ]
